SELECT TOP (1000) [Time]
      ,[Time2]
      ,[Water_Flow_Rate]
      ,[Pump_1_X_Axis]
      ,[Pump_1_Y_axis]
      ,[Pump_2_X_Axis]
      ,[Pump_2_Y_Axis]
      ,[Pump_3_X_Axis]
      ,[Pump_3_Y_Axis]
      ,[OA_TEMP]
      ,[Power_Consumption]
      ,[Pump_1_Status]
      ,[Pump_2_Status]
      ,[Pump_3_Status]
      ,[avg_outflow]
      ,[avg_inflow]
  FROM [Water Works].[dbo].[Water Pump Data]
